apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

generators:
  - ksops-generator.yaml

configMapGenerator:
  - name: gridstate-config
    namespace: gridstate
    behavior: merge
    literals:
      - REGION=region-a
