apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - redis-pvc.yaml
  - redis-configmap.yaml

generators:
  - ksops-generator.yaml

configMapGenerator:
  - name: gridstate-config
    namespace: gridstate
    behavior: merge
    literals:
      - REGION=region-a

patches:
  - path: redis-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
      namespace: gridstate
