apiVersion: v1
kind: Secret
metadata:
    name: gridstate-redis-auth
    namespace: gridstate
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:NTCx8pz0Aq3X5Pzl3xrH0QgjwKOpPto6fweZp9WKOq0=,iv:3l/miBjLOD4Rf3ZxrdNIUQgyJNKBtzS2EEl+bbFdzAQ=,tag:9K80EViSaIyO94iUv8CpIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q24wNzB5WjhZUi9YQzVs
            bWZuWmtEQTBVNVdNaGNXeXJDR1dzaGc0ZmxNCnNHdTJlVUs2UmtUZDI5akdwc2FO
            UWZnWFp1UlBRcDFuOE5rMkF5STBVUjgKLS0tIGpNdW1hRWZVa3p0dU12NjhOaS8r
            bHgwVzMxNHZMMnljNXJ3YzVDUUVHc1EKljdhonMBBwiSbYEodJWLnEW5aLqPmeNK
            kpszaXEbdoKRvjrDryVWgxR7+uWqlz4HdyBBiwzH0WO4xmnPPZX2tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5lyfs7pr09dm7nsk42f6ugzk7pvgy4x7n0xegk3sq3jlfw99v4szde2g9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T12:11:36Z"
    mac: ENC[AES256_GCM,data:NB75Y5EA53QWSRE+zpniZ0krdES2MBio6y78wMqqnX+Jc5LTgAvh8uv/b+hY3zuFlBic4rloJz4K6N5B37AxHKJfQAgnyk842PegFHjvVI1+IFBpxUYMKxkplcBZNF/T+43fKNO6hQZXmVvUW7QmjLysjksqJuvR4gYq/jAEGO8=,iv:sc6cNo3yKZ4pc8QNS3g8d07rxqI9f/i6bOiNMoiLxKE=,tag:4d9yyMqcTHbB12KQzfAsGg==,type:str]
    version: 3.13.3
