apiVersion: v1
kind: Secret
metadata:
    name: gridstate-redis-auth
    namespace: gridstate
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:qEGv9co9e4rynFgvA50YSGkpLPv6qCC3CHIExW/R4AZb6Y2DpyubWU9/W2c=,iv:EGa6Epq3rU53LoiKE70t41M9lrFckJFOYJ9iSLicCDY=,tag:vaGKU3WKJ4nBMHEp7UVPug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMzBaSHM1RTNIRGZXZWZj
            bjNvak9IODVpeG1WY2RLM0JKRjByQlVJWHpZCkVsMm1Nc3dlTTFJd1NCbGhjT25o
            NWw3VmdsalZUT0NKUHlhUlkyZS8xQmcKLS0tIEk5OVFkaVYrR25MdGNxQXRTbXdL
            OEoyUGdUS29CSFFmMmduVEw5SUE3Q1kKk+YvX0U4DZg0rPBmJP3+jARjbA2e77bX
            cY3A/rPd0MzeQ/dsFPDPVzLwXr6f3to8XYdOMBmyvZK+q9IkhBpeuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19kp0xjmqgaygghug04pdgwkf0esryatyysjqec89ctvwwjyvvsxsw06phv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T10:46:10Z"
    mac: ENC[AES256_GCM,data:D6rCpASzrxzxWasB7erXqBumd4MiattgVNB3us4U1OlwaKHY4nTTQVYITuSWG2VZNW9xa9drb/Xa2vQ0E5QsSZfDWC0vrPyXjPnqsPqJUYuGiW56FQoHFxFgx22cjFQ/yciRyXF3xEaOxwyAP8hW/Bh0kt/pvw2w3KxEFFcYNc4=,iv:MN+ia3FUvM1MBECCPbuXoQJM8h3/CMdrv0t4Kwu0UjE=,tag:eeGTWpMTD4cTNfm9guIVfw==,type:str]
    version: 3.13.3
