apiVersion: v1
kind: Secret
metadata:
    name: gridstate-redis-auth
    namespace: gridstate
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:G6Vp1c1kanML70aCNnQE5ErRULMFJyMyltglAKxxAU2htxOXe9Hy5KnBtmrdggVGp5XAht/HEr7iR1DHweQjCQ==,iv:ytOaQBSV9ZxTuVV7za3cZSLj7iWyhx3LTpMqlWfhHOE=,tag:o5Q3qWMvkgTWBK4UPSJj6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEKzZYc2dzNzhEa1E5OXRw
            ay9TZGJ4bXBKalNzbW5CaHNLTUI2eG9lcm44CldDWWgraWtzd1lQNExkSmRSNytZ
            S2tqd0R5WTVUV1NpakFETFNjZWJwMFkKLS0tIGgyUmFYR0pyOERocVVQVDEyYS9l
            TWlvOHlGY29lNFdMOHpqNm0rUVVINUUKoGzoqKO5b8g4cQUhHpQrS3UTrBJq/iYp
            0bnTV8OQYUFmmI1OJA/YwXsAsbscsJXJx7P6lr6u5Ev30WVVTm9k9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5lyfs7pr09dm7nsk42f6ugzk7pvgy4x7n0xegk3sq3jlfw99v4szde2g9
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:58:25Z"
    mac: ENC[AES256_GCM,data:1PWri/5dPISj5y48BSTapRLEaQkJOgwuTykLe9ZCCOpHyxaYOJs6A87IsW4Xsii/toI9B2weZKD5wRTHGPQUlyvoS0aYbqkkRhQtIOhK1K59ia+DGsvF0ZCQuvi1yInUWQnzp3eP6/Ebl9B4zOT4flOeKAoCTxibO1W8Qt9zqnQ=,iv:+X92F/WNhSXsJOhQDV/cfnt5R8V8csPoXBh+OhvXJik=,tag:TpNHFa/AIzFWZDY0/V+YAw==,type:str]
    version: 3.13.3
